### ISSUE TITLE
checkpoint error

### ISSUE THREAD

**Issue by madhu-korada** [maiminh1996/YOLOv3-tensorflow#20]
2019-03-28 06:17:53.366319: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key yolov3/darknet53_body/Conv/BatchNorm/beta not found in checkpoint
Traceback (most recent call last):
  File "D:\Users\madhu\Anaconda3\envs\yolo\lib\site-packages\tensorflow\python\client\session.py", line 1334, in _do_call
    return fn(*args)
  File "D:\Users\madhu\Anaconda3\envs\yolo\lib\site-packages\tensorflow\python\client\session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "D:\Users\madhu\Anaconda3\envs\yolo\lib\site-packages\tensorflow\python\client\session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key yolov3/darknet53_body/Conv/BatchNorm/beta not found in checkpoint
         [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

i got an error like this. any idea?

**Comment by madhu-korada** [comment]
I converted my weights, still i got this error

**Comment by denhpenglin** [comment]
I have this problem,do you have solve this problem?

**Comment by madhu-korada** [comment]
No i couldn't. Let me know if you can.
